from typing import overload

import numpy as np
import numpy.typing as npt

__version__: str
__id__: str

class Model:
    @overload
    def __init__(self, config: "Config") -> None: ...
    @overload
    def __init__(self, model_path: str) -> None: ...

class Tokenizer:
    def __init__(self, model: Model) -> None: ...
    def encode(self, text: str) -> npt.NDArray[np.int32]: ...

class GeneratorParams:
    def __init__(self, model: Model) -> None: ...

class Generator:
    def __init__(self, model: Model, params: GeneratorParams) -> None: ...
    def append_tokens(self, tokens: npt.NDArray[np.int32]) -> None: ...
    def get_logits(self) -> npt.NDArray[np.float32]: ...

class Config: ...
